from applications.alumniprofile.models import Degree

degrees = ['Master of Accountancy (MAcc, MAc, or MAcy)',
           'Master of Advanced Study (MAS)',
           'Master of Economics (MEcon)',
           'Master of Architecture (MArch)',
           'Master of Applied Science (MASc, MAppSc, MApplSc, MASc and MAS)',
           'Master of Arts (MA, MA, AM, or AM)',
           'Master of Arts in Teaching (MAT)',
           'Master of Arts in Liberal Studies (MA, ALM, MLA, MLS or MALS)',
           'Master of Business (MBus)',
           'Master of Business Administration (MBA or MBA)',
           'Master of Business Informatics (MBI)',
           'Master of City Planning',
           'Master of Chemistry (MChem)',
           'Master of Commerce (MCom or MComm)',
           'Master of Computational Finance (or Quantitative Finance)',
           'Master of Computer Applications (MCA)',
           'Master in Creative Technologies',
           'Master of Criminal Justice (MCJ)',
           'Master of Design (MDes, MDes or MDesign)',
           'Master of Divinity (MDiv)',
           'Master of Economics (MEcon)',
           'Master of Education (MEd, MEd, EdM, MAEd, MSEd, MSE, or MEdL)',
           'Master of Enterprise (MEnt)',
           'Master of Engineering (MEng, ME or MEng)',
           'Master of Engineering Management (MEM)',
           'Master of European Law (LLM Eur)',
           'Master of Finance (MFin)',
           'Master of Financial Mathematics (Master of Quantitative Finance)',
           'Master of Financial Engineering (Master of Quantitative Finance)',
           'Master of Financial Economics',
           'Master of Fine Arts (MFA, MFA)',
           'Master of Health Administration (MHA)',
           'Master of Health Science (MHS)',
           'Master of Humanities (MH)',
           'Master of Industrial and Labor Relations (MILR)',
           'Master of International Affairs',
           'Master of International Business',
           'Master of International Studies (MIS)',
           'Masters in International Economics',
           'Master of Information System Management ( MISM, MSIM, MIS or similar)',
           'Master of IT ( MSIT, MScIT, MScIT, MScIT or MSc IT)',
           'Master of Jurisprudence (MJ or MJur)',
           'Master of Laws (LLM or LLM)',
           'Master of Studies in Law (MSL)',
           'Master of Landscape Architecture (MArch)',
           'Master of Letters (MLitt)',
           'Master of Liberal Arts (MA, ALM, MLA, MLS or MALS)',
           'Master of Library and Information Science (MLIS)',
           'Master of Management (MM)',
           'Master of Mathematics (or MMath)',
           'Master of Mathematical Finance',
           'Master of Medical Science',
           'Master of Music (MM or MMus)',
           'Master of Occupational Therapy (OT)',
           'Master of Pharmacy (MPharm or MPharm)',
           'Master of Philosophy (MPhil)',
           'Master of Physics (MPhys)',
           'Master of Physician Assistant Studies',
           'Master of Political Science',
           'Master of Professional Studies (MPS or MPS)',
           'Master of Public Administration (MPA)',
           'Master of Public Affairs (MPAff)',
           'Master of Public Health (MPH)',
           'Master of Public Management',
           'Master of Public Policy (MPP)',
           'Master of Quantitative Finance',
           'Master of Rabbinic Studies (MRb)',
           'Master of Real Estate Development',
           'Master of Religious Education',
           'Master of Research - MSc(R)',
           'Master of Sacred Theology (STM)',
           'Master of Sacred Music (MSM)',
           'Master of Science (MSc, MSc, MSci, MSi, ScM, MS, MSHS, MS, Mag, Mg, Mgr, SM, or SM)',
           'Master of Science in Education',
           'Master of Science in Engineering (MSE)',
           'Master of Science in Finance (MFin)',
           'Master of Science in Human Resource Development (HRD or MSHRD)',
           'Master of Science in Information Systems Management (MSMIS)',
           'Master of Science in Information Systems (MSIS)',
           'Master of Science in Information Technology (MSIT, MScIT, MScIT, MScIT or MSc IT)',
           'Master of Science in Nursing (MSN)',
           'Master of Science in Project Management (MSPM)',
           'Master of Science in Management (MSc or MSM)',
           'Master of Science in Leadership (MSL)',
           'Master of Science in Supply Chain Management (SCM or MSSCM)',
           'Master of Science in Taxation',
           'Master of Science in Teaching (MST)',
           'Master of Social Work (MSW)',
           'Master of Social Science (MSSc)',
           'Master of Surgery (ChM or MS, as well as MCh and MChir)',
           'Master of Studies (MSt or MSt)',
           'Master of Theology (ThM or MTh)',
           'Master of Theological Studies (MTS)',
           'Master of Urban Planning',
           'Master of Veterinary Science (MVSC or MVSc)' ]

for d in degrees:
    d1 = Degree(degree=d)
    d1.save()
